name: "Verify type labels"

on:
  pull_request_target:
    types: [opened, labeled, unlabeled, synchronize]

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: baev/action-label-verify@main
        with:
          allowed: |
            type:bug
            type:improvement
            type:internal
            type:invalid
            type:new feature
            type:dependencies
